//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GELISTIRME
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OkulSabahDBEntities : DbContext
    {
        public OkulSabahDBEntities()
            : base("name=OkulSabahDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Siniflar> Siniflar { get; set; }
        public virtual DbSet<Bolumler> Bolumler { get; set; }
        public virtual DbSet<Ogretmenler> Ogretmenler { get; set; }
    }
}
