//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GELISTIRME
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogretmenler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogretmenler()
        {
            this.Siniflar = new HashSet<Siniflar>();
        }
    
        public int OgretmenlerID { get; set; }
        public string OgretmenTC { get; set; }
        public string OgretmenAdi { get; set; }
        public string OgretmenSoyadi { get; set; }
        public string Cinsiyet { get; set; }
        public string Telefon { get; set; }
        public string MedeniHali { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<int> DogumYeriID { get; set; }
        public string Adres { get; set; }
        public Nullable<int> KanGrubuID { get; set; }
        public Nullable<int> BransID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siniflar> Siniflar { get; set; }
    }
}
