//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GELISTIRME
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siniflar
    {
        public int SınıflarID { get; set; }
        public string SınıfNo { get; set; }
        public string SınıfSubesi { get; set; }
        public Nullable<int> OgretmenID { get; set; }
        public Nullable<int> BolumID { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        public virtual Ogretmenler Ogretmenler { get; set; }
    }
}
